### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by jy95** [jy95/Syntheses-PDF-Builder#1]
Things to do : 

1. Rename the pdf files

Using mapping in [config.yml](https://github.com/Gp2mv3/Syntheses/blob/master/src/config.yml)

```yml
- mapping:
                advSecu: Secured systems engineering
                advalgo: Advanced Algorithms for Optimization
                algo: Algorithmique et structures de données
                ananum: Analyse numérique
                archi: Architecture and performance of computer systems
                autolin: Automatique Linéaire
                ca: Complément d'analyse
                calcu: Calculabilité
                chimie: Chimie
                chimieorga: Chimie Organique
                circ: Circuits électroniques
                circmes: Circuits et Mesures
                cl: Computational Linguistics
```

use the mappings to rename the pdf file in the drive

```bash
pdflatex --jobname="Analyse numérique"  sourceFile.tex
```

[Source](http://tug.org/pipermail/pdftex/2007-April/007140.html)
